### ISSUE TITLE
你就是个傻逼智障

### ISSUE THREAD

**Issue by shuihaizi** [flyzend/HoveringScrollView#1]
你不是low货？你又有什么出息？你的眼光又有多远？你当然不是一类人，因为你就是个傻逼智障

**Comment by flyzend** [comment]
哈哈哈，我挂个签名没指名道姓，你怎么就知道我说的low货是你呢，看来你自己还是蛮有自知之明的。你别把我笑死了，哈哈哈，上次还bb的说到此为止，我就挂个签名钓鱼，鱼儿就啪啪啪的自己扇自己脸，真是太好笑了

**Comment by shuihaizi** [comment]
本来你删了就算了，还TM像太监一样阴阳怪气的逼逼，敢说还不敢承认，傻逼智障一个！你不是不删吗，真是好笑

**Comment by flyzend** [comment]
我就知道你会看啊，你这人啥样我比你还清楚，你看了low货这个词你就知道，描述的这么清楚，这不就是我自己吗。然后你果然就来了，如约而至，而你呢，一点进步都没有，还是那老词，就这？

**Comment by shuihaizi** [comment]
你喜欢那两个字，当然要多还给你啊！傻逼

**Comment by shuihaizi** [comment]
你就是个傻逼智障蠢货脑残，多发些词来形容你满意了吗

**Comment by flyzend** [comment]
你别急啊，想好了再发，每次都编辑。

是我不对，不该对你有要求，毕竟你嘴巴里也吐不出象牙。

**Comment by flyzend** [comment]
就这就这就这？

**Comment by flyzend** [comment]
最后老子挂什么签名，关你什么事，你管老子？真你妈有意思，你自己犯贱要看，自己生得贱，是我要给你看的？而且你看了就看了，非要对号入座，你自己说你咋这么贱呢，贱骨头你咋不把你眼睛挖了手剁了呢？
